apiVersion: v1
kind: Service
metadata:
  name: ecommerce-client-service
spec:
  type: LoadBalancer
  selector:
    app: ecommerce-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
